---
title: "Leaflet Dygraph Vignette"
resource_files:
- leafletvignetteDataGrab.R
- sourceData.RDat
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    source_code: embed
    
---

```{r setup, include=FALSE}
# Load packages and initialize data here
library(flexdashboard)
library(scales)
library(dygraphs)
library(leaflet)
library(macrodata)
library(dplyr)
library(countrycode)
library(ggplot2)
library(DT)

##load data
load('sourceData.RDat')

##create shading by GDP
qpal <- colorQuantile("Blues", countries$gdp_md_est, n = 20)

##create popup country name and economic stage
popup <- paste0("<strong>Country: </strong>", 
                countries$name, 
                "<br><strong>Market Stage: </strong>", 
                countries$economy)

leaf_world <- leaflet(countries) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, lat =  15, zoom = 2) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = .7, color =
      ~qpal(gdp_md_est), layerId = ~name, popup = popup)

##load up some gdp and population data
gdp2008 <- as.data.frame(countries$gdp_md_est)
rownames(gdp2008) <- countries$name
gdp2008$pop <- countries$pop_est
colnames(gdp2008) <- c("GDP", "Population")

```


World Map Time Series {data-orientation=rows}
=====================================

Sidebar {.sidebar}
-------------------------------------
  
```{r}

helpText("Select an economic time series.")

selectInput("indicatorselect2", "Choose an economic indicator", 
                          choices = c("GDP Per Capita", "GDP Per Capita Growth", 
                                      "Real Interest Rate", "Exchange Rate",
                                      "CPI", 
                                      "Labor Force Part. Rate - all"))

```

Row {data-height=650}
-------------------------------------

### World Map

```{r, echo = FALSE}

  leafletOutput("map1")

  output$map1 <- renderLeaflet({
    leaf_world
  })
```

Row {.tabset .tabset-fade}
-------------------------------------

### Economic Time Series

```{r, echo = FALSE}

dygraphOutput("dygraph2")
  
   clickedCountry <- eventReactive(input$map1_shape_click, {
     return(input$map1_shape_click$id)
     })
   
   indicatorInput2 <- reactive({
     switch(input$indicatorselect2,
         "GDP Per Capita" = WorldGDPPerCapita,
         "GDP Per Capita Growth" = WorldGDPPerCapitaGrowth,
         "Real Interest Rate" = WorldRealInterestRate, 
         "Exchange Rate" = WorldExchangeRate, 
         "CPI" = WorldCPI, 
         "Labor Force Part. Rate - all" = WorldTotalLaborPartRate)
})
   
   output$dygraph2 <- renderDygraph({
    
    ##get the economic indicator from the sidebar 
    indicator2<-indicatorInput2()
    
    ##turn the country clicked on into a country code
    code2<- countrycode(as.character(clickedCountry()), "country.name", "iso3c")
    
    dygraph(indicator2[, code2], main = clickedCountry()) %>%
      dyRangeSelector(height = 20) %>%
      dyShading(from = "2007-12-01", to = "2009-06-01", color = "#FFE6E6") %>% 
      dyEvent(x = "2008-09-15", label = "Fin Crisis", labelLoc =
      "top", color = "red")
      })
   
```


### Data Table Country Indicators

```{r}
renderDataTable({
    ##get the economic indicator from t
    indicator2<-indicatorInput2()
    
    ##turn the country clicked on into a country code
    code2<- countrycode(as.character(clickedCountry()), "country.name", "iso3c")
    
    countryData <- merge(WorldCPI[, code2], 
                         WorldExchangeRate[, code2],         
                         WorldGDPPerCapitaGrowth[, code2], 
                         WorldGDPPerCapita[, code2],
                         WorldRealInterestRate[, code2],
                         WorldTotalLaborPartRate[, code2])
    countryDataTable <- as.data.table(countryData)
    colnames(countryDataTable)<- c( "Date",
                                   "CPI", 
                                   "Exchange Rate", 
                                   "GDPPC", 
                                   "GDPPC Growth",
                                   "Int. Rate", 
                                   "Labor Part.")
    
    datatable(countryDataTable, fillContainer = TRUE)
  })

```

Linked Brushing {data-orientation=columns}
=====================================

Column {data-width=350}
-----------------------------------------------------------------------

### GDP v. Population {data-width=600}

```{r, echo=FALSE}
# Reactive that returns the whole dataset if there is no brush
selectedData <- reactive({
  req(input$plot1_brush)
  data <- brushedPoints(gdp2008, input$plot1_brush)
  if (nrow(data) == 0)
    data <- gdp2008
  data
})

plotOutput("plot1", brush = brushOpts(id = "plot1_brush"))
output$plot1 <- renderPlot({
  ggplot(gdp2008, aes(Population, GDP)) + geom_point()
})

```

Column {data-width=350}
-----------------------------------------------------------------------

### Country Details

```{r}
renderTable({
  
  selectedData()
})
```



