---
title: "WDI Map dataGrab"
output: html_notebook
---



```{r}
##the packages we need to grab the map data
library(rnaturalearth)
library(sf)
##the packages we need to grab the macroeconomic data
devtools::install_github("regisely/macrodata")
library(macrodata)
library(Quandl)
```

```{r}
## Have a look at this in the global environment after it is loaded
## it contains the shape file, and population and gdp data, amongst other things
library(leaflet)
world <- ne_countries(type = "countries")

##create shading by GDP
qpal <- colorQuantile("Blues", world$gdp_md_est, n = 20)

##create popup country name and economic stage
popup <- paste0("<strong>Country: </strong>", 
                world$name, 
                "<br><strong>Market Stage: </strong>", 
                world$economy)

leaf_world <- leaflet(world) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  setView(lng =  20, lat =  15, zoom = 2) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = .7, color =
      ~qpal(gdp_md_est), layerId = ~iso_a3, popup = popup)

```

```{r}

# Quandl key from quandl.com
# Quandl is a source of world macroeconomic data and is free
# in this case we will pull in world bank data
# but we're not going to do it directly, we're going to use the package called "macrodata" to do so. why? 
# Quandl does not allow a user to pull in download multiple data sets on multiple countries with one
# command
library(Quandl)
Quandl.api_key("iz-ThHX9dpWweuxYW43a")

# get econ data for all countries
# serachQ is part of the macrodata package
# see here for more info: http://regisely.com/blog/macrodata/

econIndicators <- searchQ("gdp per capita exchange rate population growth consumer price index real interest
                          rate labor force", country = "Brazil", frequency = "annual", database = "WWDI")

# select out the time series we want
# note: this takes quite a while - 5 to 10 minutes
# Why? we are downloading 7 data sets, from 1960 to 2015, on every country in the world

econData <- requestQ(econIndicators, c(17, 3, 1, 10, 19, 6))

# Usually the names we give to list objects are a convenience
# here it is crucial because we are going to refer to these names in our flexdashboard
# the names will be the inputs to be selected by the user; they have to match exactly

names(econData) <- c("GDP Per Capita", "GDP Per Capita Growth", "Real Interest Rate", 
                     "Exchange Rate", "CPI", "Labor Force Part. Rate")
library(tidyquant)
dataset <- paste("WWDI/", "USA", "_FR_INR_RINR", sep = "")
test <- Quandl(dataset, order = "asc")

countryData <- econData %>% lapply(., function(x) {merge(x[, "USA"])}) %>%
  as.data.table() %>%
  mutate_each(funs(round(.,2))) %>% 
  mutate(Date = seq(mdy('12/31/1960'), mdy('12/31/2015'), by='years')) %>% 
  setcolorder(., c(length(.), 1:(length(.)-1)))
library(DT)
datatable(countryData, fillContainer = TRUE, 
          caption = "Economic Data",  options = list(dom = 't'))
```



```{r}
# Save
save(leaf_world, world, file = 'wdiMapData.RDat')
```

